<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Quantity1</name>
   <tag></tag>
   <elementGuidId>c136e016-a420-40a6-83d7-e87132ac1183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='a-autoid-4-announce']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a-autoid-4-announce</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c46118f3-6976-4819-80ad-5d5440d201b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-text a-declarative</value>
      <webElementGuid>b3dd7ddf-4520-421c-87dc-cb5ea2e07f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-func-deps</name>
      <type>Main</type>
      <value>aui-da-a-dropdown-button</value>
      <webElementGuid>f8af78e9-b8d9-42b2-b9c1-b3a231d286c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-type</name>
      <type>Main</type>
      <value>widget</value>
      <webElementGuid>f557ff4a-5cb4-4472-8899-a923ae0578c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-interaction-events</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>bc6cbd86-e7fa-4bfe-96a5-87a0d24d92eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action</name>
      <type>Main</type>
      <value>a-dropdown-button</value>
      <webElementGuid>b9fa1f50-756c-4348-b664-165871050791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4cc6e571-0f7d-4c97-b7d1-c58778541073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a-autoid-4-announce</value>
      <webElementGuid>c923f9e4-d3e0-4bc3-9956-0255f3bd0fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-csa-c-id</name>
      <type>Main</type>
      <value>1hav5n-tyw0ne-ahbd7c-jxodlv</value>
      <webElementGuid>4d6c6f0e-e055-41f3-8324-fd5b98e2aa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quantity:1 </value>
      <webElementGuid>4d12ccaf-828f-40de-83e3-4c1f0dabde68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a-autoid-4-announce&quot;)</value>
      <webElementGuid>a382600a-0187-48e8-ab4a-aaffaf501dc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-4-announce']</value>
      <webElementGuid>33ba8323-6eb2-4643-82c3-6c9ccd749b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='a-autoid-4']/span/span</value>
      <webElementGuid>18093259-3f2b-4990-ac3d-9f05294aecfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span/span/span</value>
      <webElementGuid>5f589d71-466c-455c-a1b0-ec9b918a0659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'a-autoid-4-announce' and (text() = 'Quantity:1 ' or . = 'Quantity:1 ')]</value>
      <webElementGuid>0146d62d-3aef-4885-ae46-f2b08856e49d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
