<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_a-button-input</name>
   <tag></tag>
   <elementGuidId>09ee0d09-759b-4541-a233-7ed553c9288a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='submit'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.a-button-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80a693ed-967a-4b0e-bf5a-f718a48ae053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-params</name>
      <type>Main</type>
      <value>{&quot;toasterType&quot;:&quot;AIS_INGRESS&quot;}</value>
      <webElementGuid>95b78a8f-e393-4b76-ba66-8c6c2bfb3919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-type</name>
      <type>Main</type>
      <value>DISMISS</value>
      <webElementGuid>e14e122f-3a88-4ad5-85a0-b16ad54a1e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>5c72cf2c-dfb9-45f5-aea4-df1f6b197960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5830f860-2f32-48f0-b9a1-9efd37a847e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-main&quot;)/div[@class=&quot;nav-left&quot;]/div[@class=&quot;a-section glow-toaster glow-toaster-theme-default glow-toaster-slot-default nav-coreFlyout nav-flyout&quot;]/div[@class=&quot;glow-toaster-content&quot;]/div[@class=&quot;glow-toaster-footer&quot;]/span[@class=&quot;a-button a-spacing-top-base a-button-base glow-toaster-button glow-toaster-button-dismiss a-button-focus&quot;]/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>6cb3ad06-a9d2-45a0-ab1c-cad169ae1e73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='submit'])[2]</value>
      <webElementGuid>021f10f1-e890-4bb6-81fb-d24f96cdc68f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-main']/div/div/div/div[3]/span/span/input</value>
      <webElementGuid>6b6c7bcb-5b66-439f-a2a5-2bf397da4a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>1a462bdf-7f08-4101-84ed-0399a2807e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>8861adc2-9059-453a-8feb-27a43d2867aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
