<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_code_1</name>
   <tag></tag>
   <elementGuidId>3466aa77-a8ba-410f-94b8-d0e0244793bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27bd02fd-3ead-4479-81bf-783515592ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b211f84b-2b3a-421c-88e2-5e346a80eaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>73574c3f-20c0-444b-9dea-a75b6ca1db76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fc9a7f30-7760-44b6-9a73-572315371f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>cf7ea79e-1445-4688-b18a-cbfcdfa71ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-input-text a-span12 cvf-widget-input cvf-widget-input-code</value>
      <webElementGuid>26a6f1c1-4896-48f6-aae6-bfe84bc6bca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvf-page-content&quot;)/div[@class=&quot;a-box&quot;]/div[@class=&quot;a-box-inner a-padding-extra-large&quot;]/form[@class=&quot;cvf-widget-form a-spacing-none&quot;]/div[@class=&quot;a-row&quot;]/div[@class=&quot;a-row a-spacing-base&quot;]/input[@class=&quot;a-input-text a-span12 cvf-widget-input cvf-widget-input-code&quot;]</value>
      <webElementGuid>b734d961-bf0d-4ec5-95a2-cc988d8f6697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='code']</value>
      <webElementGuid>08149227-74df-4b3a-b2c0-3f2fa817e25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cvf-page-content']/div/div/form/div/div[5]/input</value>
      <webElementGuid>3fcb60a2-d0fd-4a66-bf17-a2b6d7eac867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>712557ea-cb09-44df-b0c9-a837186fc207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'code']</value>
      <webElementGuid>92b77af4-292a-4f2a-9547-88b6b0827bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
